#include<bits/stdc++.h>
using namespace std;
//Graph travers korar jonno BFS algorithme use kora hoy.
//Breadth First Search Level Order e kaj kore.
//Ektu graph e visited node track rakhar jonno n size er ekti array, vector noy array declare kora hoy. zekhane sob gulu node er value false kora thake. false thaka mane visit hoyni,visit korar sathe sathe true kora hobe. BFS e level order thik thake kintu ekti level er sob gulu node er order change hote pare.
int main(){
    
    return 0;
}